language: csharp
solution: "./Extension Library/Extension Library.sln"
install:
  - nuget restore "./Extension Library/Extension Library.sln"
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release "./Extension Library/Extension Library.sln"
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe "./Extension Library/ArrayExtensionTests/bin/Release/MyProject.Tests.dll"
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Extension Library/EnumerableExtensionTests/bin/Release/MyProject.Tests.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Extension Library/StringExtensionTests/bin/Release/MyProject.Tests.dll
branches:
only:
  - master